### ISSUE TITLE
The control buttons take long to hide!

### ISSUE THREAD

**Issue by Hussseinkizz** [lewhunt/react-tv-player#1]
Hey nice work, I think though the control buttons take long to hide after one removes focus from them, like I think they should disappear like a few minutes after mouse leave, but nice!

**Comment by lewhunt** [comment]
Hey, thank for trying it out.

I mainly targeted arrow keys for TV, so I will look at speeding up the hide when using mouse input. Cheers

**Comment by Hussseinkizz** [comment]
ok that will be cool

**Comment by lewhunt** [comment]
I've taken overlay timeout down to 4 seconds and added a mouseleave event to hide overlay when cursor leaves window during playback. 

May decide to take it down further in the future 🙌

**Comment by lewhunt** [comment]
Hey, just to let you know there is now a new feature to press up to immediately clear the buttons.

**Comment by Hussseinkizz** [comment]
hmm that's nice, let me check it out, nice!
