### ISSUE TITLE
Libraries must not initialize dependencies or set global CSS attributes

### ISSUE THREAD

**Issue by arjunindia** [lewhunt/react-tv-player#18]
At https://github.com/lewhunt/react-tv-player/blob/215f7d7cc08319f4a2a30fa642106d560cbacb3b/src/lib/TVPlayer.tsx#L92 the library sets document body styles. This should not be done and must be handed over to the user for their preference, especially considering the fact that it might break or alter the user's existing UI
and at https://github.com/lewhunt/react-tv-player/blob/215f7d7cc08319f4a2a30fa642106d560cbacb3b/src/lib/TVPlayer.tsx#L19
the spacial navigation library is initialized. This also should be removed from the library and the initialization must be done by the library user - since it will cause for two separate instances each working independently if the user already uses the library for their own UI, causing issues while navigating and unexpected behavior.

**Comment by lewhunt** [comment]
Thanks for raising this issue. I understand the concerns about initialising dependencies and setting global CSS attributes directly within the library. Worth noting there can be scenarios where library-level initialisation simplifies integration, particularly for users needing quick and easy setup without extensive configuration. To address this, I've added prop disableInitNav. This will allow users to opt out of initialising navigation, giving more control over their implementation of the spatial navigation library. This approach aims to balance ease of integration for new users while providing flexibility for those with more complex requirements. Cheers, L
