### ISSUE TITLE
Question Regarding YouTube Play Button Rendering Issue in TVPlayer Component

### ISSUE THREAD

**Issue by rossanodr** [lewhunt/react-tv-player#20]
In the example shown, the YouTube play button is not rendered when I try to use the component:

```

<TVPlayer
    url="https://www.youtube.com/watch?v=SkVqJ1SGeL0"
    mediaIndex={0}
    playsinline={true}
    hideControlsOnArrowUp={true}
    disableFullscreen={false}
    disableInitNav={true}
/>
```
The YouTube 'Play' button appears underneath.

![image](https://github.com/user-attachments/assets/b27f4357-c770-4802-9554-1cccb1a30ffa)

**Comment by lewhunt** [comment]
Hi, 

Thanks for taking a look at the component.

This player component is designed for big-screen devices and the play button is intended to sit underneath - in the row of buttons below the title. The red YouTube play button can be covered up with an image using the **light** preview prop - see the readme and demo code.

Let me know if I've misunderstood.

Cheers
Lewis

**Comment by lewhunt** [comment]
try adding `light={true}` and it will pick up the YouTube preview image

```
<TVPlayer
    url="https://www.youtube.com/watch?v=SkVqJ1SGeL0"
    mediaIndex={0}
    playsinline={true}
    hideControlsOnArrowUp={true}
    disableFullscreen={false}
    disableInitNav={true}
    light={true}
/>

**Comment by rossanodr** [comment]
> try adding `light={true}` and it will pick up the YouTube preview image
> 
> ```
> <TVPlayer
>     url="https://www.youtube.com/watch?v=SkVqJ1SGeL0"
>     mediaIndex={0}
>     playsinline={true}
>     hideControlsOnArrowUp={true}
>     disableFullscreen={false}
>     disableInitNav={true}
>     light={true}
> />
> ```

Thanks for replying! I just want to congratulate you. I've been trying to make a component like this for a while and kept running into issues. Your project is amazing and exactly what I needed. You've really saved me
thank you so much!

**Comment by rossanodr** [comment]
I understand that this project was designed for larger displays, but I was wondering if there’s a way to implement playback speed control and if it might be possible to hide the YouTube buttons on smaller screens for a cleaner look.

> Hi,
> 
> Thanks for taking a look at the component.
> 
> This player component is designed for big-screen devices and the play button is intended to sit underneath - in the row of buttons below the title. The red YouTube play button can be covered up with an image using the **light** preview prop - see the readme and demo code.
> 
> Let me know if I've misunderstood.
> 
> Cheers Lewis

**Comment by lewhunt** [comment]
I think you could try the playbackRate prop for speed. Or build a custom button for more control.

Initiating YouTube playback and covering its buttons on smaller mobile devices is more tricky I’m afraid, it is often blocked.

**Comment by rossanodr** [comment]
> I think you could try the playbackRate prop for speed. Or build a custom button for more control.
> 
> Initiating YouTube playback and covering its buttons on smaller mobile devices is more tricky I’m afraid, it is often blocked.

Even though the video display is reduced, I can't shrink the player size.

`  const WrapperComponent: React.FC<{ children: ReactNode }> = ({
        children,
    }) => (
        <div
            style={{
                width: "100%",
                maxWidth: "250px",
                height: "250px",
                overflow: "hidden",
            }}
        >
            {children}
        </div>
    );

<TVPlayer
                            url="https://www.youtube.com/watch?v=SkVqJ1SGeL0"
                            light={true}
                            height={"250px"}
                            width={'500px'}
                            style={{ height: '250px', maxHeight: '250px', width: '250px' }}
                            wrapper={WrapperComponent}
                        />`
![image](https://github.com/user-attachments/assets/7afda8e1-3c19-425c-b6ce-d5d72880e946)

**Comment by lewhunt** [comment]
Yeah I’m afraid it hasn’t been built or designed for handling small sizes like that. If you remove any sizings it _might_ resize ok but I’m not sure. 

Try taking at look at the more generic [react player](https://github.com/cookpete/react-player) component for smaller screens
