### ISSUE TITLE
Audio Track supported ?

### ISSUE THREAD

**Issue by AmirKaftari** [lewhunt/react-tv-player#7]
this component support audio track and subtitles?
and related icons for audio track and subtitles can show in player ui ?

**Comment by lewhunt** [comment]
Hi,

ReactTVPlayer builds on top of (and extends) react-player, which is supposed to support multiple tracks for subtitles:
https://github.com/cookpete/react-player#multiple-sources-and-tracks

Try passing in a config prop like below:
```
<TVPlayer
  url={your_url}
  config={{ file: {
    tracks: [
      {kind: 'subtitles', src: 'subs/subtitles.en.vtt', srcLang: 'en', default: true},
      {kind: 'subtitles', src: 'subs/subtitles.ja.vtt', srcLang: 'ja'},
      {kind: 'subtitles', src: 'subs/subtitles.de.vtt', srcLang: 'de'}
    ]
  }}}
/>
```

For audio tracks you may be able to do that with JavaScript via the video element (hook into player.getInternalPlayer() to get the video element)

You can add additional UI buttons for your own functionality. See https://github.com/lewhunt/react-tv-player#custom-buttons that shows an example of adding a custom button. You'd also need to add overlay UI for changing the default subtitle track, this currently isn't part of the component.

Cheers,
Lewis

**Comment by AmirKaftari** [comment]
hi again.
can we set src for subtitle from external url like this :
http://188.121.117.29:84/api/subtitle/121150.vtt

if answer yes, we are set this now but not working. can u explain this for us ?

**Comment by lewhunt** [comment]
Please see https://github.com/lewhunt/react-tv-player/issues/9 for working solution and explanation.
