### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by AmirKaftari** [lewhunt/react-tv-player#8]
i have this error, when go to TvPlayer component.

react-dom.development.js:18572 The above error occurred in the <gb> component and Uncaught TypeError: Cannot read properties of null (reading 'useRef') 

my react version is 18.1.0.

can u help me ?

**Comment by lewhunt** [comment]
Hi,

Sorry to hear you're having problems with the component and react 18.1.

The component was built with React 18.2. 

Until I'm able to resolve it to work with 18.1, are you able to bump up the version of react you are using? I've tested TvPlayer in a bare bones Create React App with latest React 18.2 and it works ok.

You can share your repo if you like and I can take a closer look.

**Comment by lewhunt** [comment]
p.s. I've just tried updating my CRA with React 18.1 and it works. Try the following:
1) delete your node_modules folder
2) run npm i to re-install everything
3) restart your app (npm start for create react apps)

**Comment by AmirKaftari** [comment]
in my case. not working in 18.1 version of react

**Comment by lewhunt** [comment]
ok, in that case please try suggestions in my first comment.

Alternatively you could download the lib folder in this repo and import it as a local component, along with its dependencies.

**Comment by lewhunt** [comment]
Hi @AmirKaftari, based on your latest attempts with subtitles, just curious how you got around this issue...
