### ISSUE TITLE
Can not set subtitle from url link

### ISSUE THREAD

**Issue by AmirKaftari** [lewhunt/react-tv-player#9]
hi again.
can we set src for subtitle from external url like this :
http://188.121.117.29:84/api/subtitle/121150.vtt

if answer yes, we are set this now but not working. can u explain this for us ?

**Comment by lewhunt** [comment]
Hi,

I cannot access that vtt file but I've added a new branch with an mp4 that supports subtitles track, and a vtt subtitles file, so you can see the code changes needed for subtitles to work:

Branch with code additions:
https://github.com/lewhunt/react-tv-player/compare/main...subtitle-test

Screenshot:
<img width="1464" alt="Screenshot 2023-11-28 at 13 59 32" src="https://github.com/lewhunt/react-tv-player/assets/9886284/b031455e-ee43-4542-a2b7-9a73235b99bc">

Remember that this component is using [react-player ](https://github.com/cookpete/react-player)under the hood, so I suggest take a look at that repo for specifics and issues on how it supports subtitles.
